networks:
  nginx:
    external: true
services:
  backend-api:
    build: /opt/dateme/source/api
    container_name: dateme-api
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - nginx
    volumes:
      - /opt/dateme/api/reviews.json:/app/data/reviews.json
      - /opt/dateme/api/admin.json:/app/data/admin.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/admin/settings"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: /opt/dateme/source/frontend
      dockerfile: Dockerfile
    container_name: dateme-frontend
    environment:
      - REACT_APP_API_URL=http://backend-api:3001
    depends_on:
      - backend-api
    restart: unless-stopped
    networks:
      - nginx
    volumes:
      - /opt/dateme/frontend:/usr/share/nginx/html


volumes:
  data-volumes:
